### ISSUE TITLE
weird statistics while loading audiovisual collection data using sparql update

### ISSUE THREAD

**Issue by wmelder** [jrvosse/ClioPatriaDocker#2]
our data is structured as programs that contain carriers, publications and can be part of a season or series and can contain segments as well as metadata for the program itself, like title, creator, etc.

The pipeline we have installed here is OAIPMH => XSLT => XSMLRDF => Graph => Turtle => SPARQL INSERT.

Around 2M triples were loaded when I stopped the process.. What seems to happen is that initially programs, etc. load properly, but then miraculously  the carriers, titles, etc. keep increasing but not the programs and segments, that both may contain carriers and titles.

Here's a list_classes overview: 
`/browse/list_classes?graph=http%3A%2F%2Fdata.rdlabs.beeldengeluid.nl%2Flod%2F`

Class | #Instances
-- | --
schema::Carrier | 101031
schema::Context | 15848
schema::Creator | 25753
schema::Language | 11886
schema::Producer | 21791
schema::Productioncountry | 13867
schema::Program | 8
schema::Publication | 15848
schema::Recording | 7924
schema::Season | 9
schema::Segment | 7
schema::Title | 39620

When listing programs with `browse/list_instances?graph=http%3A//data.rdlabs.beeldengeluid.nl/lod/&class=http%3A//data.rdlabs.beeldengeluid.nl/schema/Program` I get way too many properties (first columns are program instances):

Instance | #Properties
-- | --
?:5237210 | 23785
?:5354043 | 25767
?:5354463 | 23785
?:5374735 | 29753
?:5382352 | 9918
?:5382353 | 9918
?:5382354 | 11899
?:5382355 | 9918

How come Cliopatria is loading properties to the wrong programs? It's not the data itself, I think, because I also loaded some on a Virtuoso instance and the number of programs was way higher. It seems like a bug. Can it have something to do with the amount of data sent via SPARQL UPDATE? Is INSERT DATA a safe way to load data?

**Comment by jrvosse** [comment]
Hi Willem, thanks for reporting this. 
Procedural: I do not believe this has anything todo with the Docker image of ClioPatria, so I think we best continue this at https://github.com/ClioPatria/ClioPatria

It would help if you could provide us with a small example to help debugging. In the mean time, could you try to load the graph as a plain RDF file, so without the SPARQL insert data statement?

Loading of plain RDF, in .xml, .nt, n3 has had many years of testing, so I expect this would go ok. My gut feeling is that the bug is in the implementation of the INSERT DATA, possibly triggered by an error in the RDF.

Success, Jacco

**Comment by wmelder** [comment]
Thanks Jacco, for pointing at the cliopatria repo. I will report issues that look like cliopatria bugs there.
For the moment I am pursuing with  SPARQL UPDATE and LOAD queries that get the data from a resourceIRI. This way I might prevent too large queries. This also is to be a problem with loading the stuff into Virtuoso, so cutting the data up might also mitigate the error in Cliopatria. Regards, Willem
